[package]
name = "drk-core"
version = "0.1.0"
edition = "2021"

[dependencies]
drk-api = { path = "../drk-api" }
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
walkdir = "2.3" # To scan folders