[package]
name = "drk"
version = "0.1.0"
edition = "2021"

[dependencies]
drk-core = { path = "../drk-core" }
drk-basic = { path = "../plugins/drk-basic" } # Built-in dependency
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
serde = "1.0"
toml = "0.8"
directories = "5.0"